package com.example.android.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

import java.util.Date;

/**
 *
 * 本地机器的设置信息
 * Entity mapped to table "SETTING".
 */
@Entity
public class Setting {
    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String ip;
    private String mask;
    private String dns;
    private String gateway;
    private String serverIp; //192.168.8.16
    private Integer serverPort;//8280
    private String videoIp;//192.168.8.16
    private Integer videoPort;//7781
    private String spareIp;//192.168.8.16
    private Integer sparePort;//7781
    private String status;
    private java.util.Date modTime;
    private Integer num;
    private String opened;
    private String oufk;
    private String ouname;
    private String code;
    private String serverId;
    private String type;
    private String usetype;
    private String alarmReportWaitTime;
    private String alarmStrategyMode;
    private String relatedMode;
    private String js;
    private String maxalarm;
    @Generated(hash = 1697630732)
    public Setting(Long id, String name, String ip, String mask, String dns, String gateway,
            String serverIp, Integer serverPort, String videoIp, Integer videoPort, String spareIp,
            Integer sparePort, String status, java.util.Date modTime, Integer num, String opened,
            String oufk, String ouname, String code, String serverId, String type, String usetype,
            String alarmReportWaitTime, String alarmStrategyMode, String relatedMode, String js,
            String maxalarm) {
        this.id = id;
        this.name = name;
        this.ip = ip;
        this.mask = mask;
        this.dns = dns;
        this.gateway = gateway;
        this.serverIp = serverIp;
        this.serverPort = serverPort;
        this.videoIp = videoIp;
        this.videoPort = videoPort;
        this.spareIp = spareIp;
        this.sparePort = sparePort;
        this.status = status;
        this.modTime = modTime;
        this.num = num;
        this.opened = opened;
        this.oufk = oufk;
        this.ouname = ouname;
        this.code = code;
        this.serverId = serverId;
        this.type = type;
        this.usetype = usetype;
        this.alarmReportWaitTime = alarmReportWaitTime;
        this.alarmStrategyMode = alarmStrategyMode;
        this.relatedMode = relatedMode;
        this.js = js;
        this.maxalarm = maxalarm;
    }
    @Generated(hash = 909716735)
    public Setting() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getIp() {
        return this.ip;
    }
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getMask() {
        return this.mask;
    }
    public void setMask(String mask) {
        this.mask = mask;
    }
    public String getDns() {
        return this.dns;
    }
    public void setDns(String dns) {
        this.dns = dns;
    }
    public String getGateway() {
        return this.gateway;
    }
    public void setGateway(String gateway) {
        this.gateway = gateway;
    }
    public String getServerIp() {
        return this.serverIp;
    }
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }
    public Integer getServerPort() {
        return this.serverPort;
    }
    public void setServerPort(Integer serverPort) {
        this.serverPort = serverPort;
    }
    public String getVideoIp() {
        return this.videoIp;
    }
    public void setVideoIp(String videoIp) {
        this.videoIp = videoIp;
    }
    public Integer getVideoPort() {
        return this.videoPort;
    }
    public void setVideoPort(Integer videoPort) {
        this.videoPort = videoPort;
    }
    public String getSpareIp() {
        return this.spareIp;
    }
    public void setSpareIp(String spareIp) {
        this.spareIp = spareIp;
    }
    public Integer getSparePort() {
        return this.sparePort;
    }
    public void setSparePort(Integer sparePort) {
        this.sparePort = sparePort;
    }
    public String getStatus() {
        return this.status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
    public java.util.Date getModTime() {
        return this.modTime;
    }
    public void setModTime(java.util.Date modTime) {
        this.modTime = modTime;
    }
    public Integer getNum() {
        return this.num;
    }
    public void setNum(Integer num) {
        this.num = num;
    }
    public String getOpened() {
        return this.opened;
    }
    public void setOpened(String opened) {
        this.opened = opened;
    }
    public String getOufk() {
        return this.oufk;
    }
    public void setOufk(String oufk) {
        this.oufk = oufk;
    }
    public String getOuname() {
        return this.ouname;
    }
    public void setOuname(String ouname) {
        this.ouname = ouname;
    }
    public String getCode() {
        return this.code;
    }
    public void setCode(String code) {
        this.code = code;
    }
    public String getServerId() {
        return this.serverId;
    }
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }
    public String getType() {
        return this.type;
    }
    public void setType(String type) {
        this.type = type;
    }
    public String getUsetype() {
        return this.usetype;
    }
    public void setUsetype(String usetype) {
        this.usetype = usetype;
    }
    public String getAlarmReportWaitTime() {
        return this.alarmReportWaitTime;
    }
    public void setAlarmReportWaitTime(String alarmReportWaitTime) {
        this.alarmReportWaitTime = alarmReportWaitTime;
    }
    public String getAlarmStrategyMode() {
        return this.alarmStrategyMode;
    }
    public void setAlarmStrategyMode(String alarmStrategyMode) {
        this.alarmStrategyMode = alarmStrategyMode;
    }
    public String getRelatedMode() {
        return this.relatedMode;
    }
    public void setRelatedMode(String relatedMode) {
        this.relatedMode = relatedMode;
    }
    public String getJs() {
        return this.js;
    }
    public void setJs(String js) {
        this.js = js;
    }
    public String getMaxalarm() {
        return this.maxalarm;
    }
    public void setMaxalarm(String maxalarm) {
        this.maxalarm = maxalarm;
    }
   
}
